update github workflow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -4,29 +4,35 @@ on:
   push:
     branches:
       - main
+
   pull_request:
     branches:
       - main
 
 jobs:
-   test:
-       runs-on: ubuntu-latest
-       steps:
-          - name: checkout main branch
-            uses: actions/checkout@v6
-          
-          - name: install python
-            uses: actions/setup-python@v5
-            with: 
-                python-version: '3.11'
+  test:
+    runs-on: ubuntu-latest
 
-          - name: Install dependencies
-            run: |
-              python -m pip install -U pip wheel
-              python -m pip install -e ".[dev]"
-          - name: Quick CLI smoke test
-            run: units-convert --help || (echo "CLI is missing" && exit 1)
+    strategy:
+      matrix:
+        python-version: ['3.10', '3.11', '3.12']
 
-          - name: Run tests
-            run: pytest
-          
+    steps:
+      - name: Checkout main branch
+        uses: actions/checkout@v6
+
+      - name: Install Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v5
+        with:
+          python-version: ${{ matrix.python-version }}
+
+      - name: Install dependencies
+        run: |
+          python -m pip install -U pip wheel
+          python -m pip install -e ".[dev]"
+
+      - name: Quick CLI smoke test
+        run: units-convert --help || (echo "CLI is missing" && exit 1)
+
+      - name: Run tests
+        run: pytest
