update github workflow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -25,9 +25,8 @@ jobs:
               python -m pip install -U pip wheel
               python -m pip install -e ".[dev]"
           - name: Quick CLI smoke test
-            run: units-convert --help || (echo "CLI is missing" && exist 1)
+            run: units-convert --help || (echo "CLI is missing" && exit 1)
 
           - name: Run tests
-            run:
-              pytest
+            run: pytest
           
